application: learn-hema
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*)/
  static_files: public/\1/index.html
  upload: public/(.*)/index.html

# site root
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /
  static_dir: public